import { useEffect, useState } from 'react';
import axios from 'axios';
import { toast } from 'react-toastify';

const money = n => `₹${Number(n || 0).toLocaleString('en-IN')}`;

export default function AdminPage() {
  const [data, setData] = useState(null);
  useEffect(() => { axios.get('/api/admin/overview').then(r => setData(r.data)).catch(e => toast.error(e.response?.data?.message || 'Admin access required.')); }, []);
  if (!data) return <div className="min-h-[calc(100vh-72px)] bg-slate-50 p-8"><div className="mx-auto max-w-7xl rounded-3xl bg-white p-8 text-center shadow-sm"><h1 className="text-2xl font-black">Loading admin console…</h1><p className="mt-2 text-sm text-slate-500">If access is denied, configure ADMIN_EMAILS on the server.</p></div></div>;
  return <div className="min-h-[calc(100vh-72px)] bg-slate-50"><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Administration</p><h1 className="mt-2 text-4xl font-black">Platform overview</h1></div></section><main className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-400">Users</p><p className="mt-2 text-3xl font-black">{data.users}</p></div><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-400">Campaigns</p><p className="mt-2 text-3xl font-black">{data.campaigns.length}</p></div><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-400">Successful payments</p><p className="mt-2 text-3xl font-black">{data.paymentSummary.paid}</p></div><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-400">Gross funded</p><p className="mt-2 text-3xl font-black">{money(data.paymentSummary.gross)}</p></div></div><section className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h2 className="text-2xl font-black">Campaign moderation view</h2><p className="mt-1 text-sm text-slate-500">Read-only operational overview for the configured administrators.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead><tr className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><th className="px-5 py-4">Campaign</th><th className="px-5 py-4">Creator</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Funding</th></tr></thead><tbody>{data.campaigns.map(c => <tr key={c._id} className="border-b border-slate-50 text-sm"><td className="px-5 py-4 font-bold">{c.title}</td><td className="px-5 py-4 text-slate-500">{c.creator?.name || c.creator?.email || '—'}</td><td className="px-5 py-4 font-bold uppercase text-emerald-600">{c.status}</td><td className="px-5 py-4">{money(c.amountRaised)} / {money(c.goalAmount)}</td></tr>)}</tbody></table></div></section></main></div>;
}
